encoding: utf-8
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
url: http://radhepatel.com
title: Radhe Patel
description: I am an Urban Fellow interested in international relations, development, local government, economics, South Asian political engagement, and exploring how to promote equity and access in NYC.
